# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_control', models.BooleanField(default=False)),
                ('agg_transfer_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('compressed_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestConceptAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_reached', models.NullBooleanField()),
                ('solution_strategy', models.CharField(default='', max_length=255)),
                ('confidence_level', models.IntegerField(null=True)),
                ('solution_score', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('familiarity1', models.IntegerField()),
                ('familiarity2', models.IntegerField()),
                ('familiarity3', models.IntegerField()),
                ('aha_during_explanation', models.BooleanField()),
                ('surprise_rating', models.IntegerField(null=True)),
                ('is_control', models.BooleanField()),
                ('too_easy', models.BooleanField(default=False)),
                ('too_hard', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Participant')),
                ('test_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.TestConcept')),
            ],
        ),
        migrations.CreateModel(
            name='TransferTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aha_during_transfer', models.NullBooleanField()),
                ('notes', models.CharField(default='', max_length=255, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Participant')),
                ('test_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.TestConceptAnswer')),
            ],
        ),
    ]
