# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testconceptanswer',
            name='too_easy',
        ),
        migrations.RemoveField(
            model_name='testconceptanswer',
            name='too_hard',
        ),
        migrations.AddField(
            model_name='testconcept',
            name='too_easy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testconcept',
            name='too_hard',
            field=models.BooleanField(default=False),
        ),
    ]
