# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20170429_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertest',
            old_name='test_concept',
            new_name='test_concept_answer',
        ),
    ]
