# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170429_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertest',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.TestConcept'),
        ),
    ]
