# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_transfertest_test_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconcept',
            name='percentage_score',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
