# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_testconcept_percentage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconcept',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
