# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_testconcept_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconceptanswer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transfertest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
