# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20170429_0321'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testconcept',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='testconceptanswer',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transfertest',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='testconcept',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
    ]
