# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20170429_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testconcept',
            name='is_control',
        ),
    ]
